// Auto-generated by avdl-compiler v1.3.9 (https://github.com/keybase/node-avdl-compiler)
//   Input file: avdl/keybase1/kbfsmount.avdl

package keybase1

import (
	"github.com/keybase/go-framed-msgpack-rpc/rpc"
	context "golang.org/x/net/context"
)

type GetCurrentDriveLetterArg struct {
}

type GetAllAvailableDriveLettersArg struct {
}

type SetCurrentDriveLetterArg struct {
	Drive string `codec:"drive" json:"drive"`
}

type KbfsMountInterface interface {
	GetCurrentDriveLetter(context.Context) (string, error)
	GetAllAvailableDriveLetters(context.Context) ([]string, error)
	SetCurrentDriveLetter(context.Context, string) error
}

func KbfsMountProtocol(i KbfsMountInterface) rpc.Protocol {
	return rpc.Protocol{
		Name: "keybase.1.kbfsMount",
		Methods: map[string]rpc.ServeHandlerDescription{
			"GetCurrentDriveLetter": {
				MakeArg: func() interface{} {
					ret := make([]GetCurrentDriveLetterArg, 1)
					return &ret
				},
				Handler: func(ctx context.Context, args interface{}) (ret interface{}, err error) {
					ret, err = i.GetCurrentDriveLetter(ctx)
					return
				},
				MethodType: rpc.MethodCall,
			},
			"GetAllAvailableDriveLetters": {
				MakeArg: func() interface{} {
					ret := make([]GetAllAvailableDriveLettersArg, 1)
					return &ret
				},
				Handler: func(ctx context.Context, args interface{}) (ret interface{}, err error) {
					ret, err = i.GetAllAvailableDriveLetters(ctx)
					return
				},
				MethodType: rpc.MethodCall,
			},
			"SetCurrentDriveLetter": {
				MakeArg: func() interface{} {
					ret := make([]SetCurrentDriveLetterArg, 1)
					return &ret
				},
				Handler: func(ctx context.Context, args interface{}) (ret interface{}, err error) {
					typedArgs, ok := args.(*[]SetCurrentDriveLetterArg)
					if !ok {
						err = rpc.NewTypeError((*[]SetCurrentDriveLetterArg)(nil), args)
						return
					}
					err = i.SetCurrentDriveLetter(ctx, (*typedArgs)[0].Drive)
					return
				},
				MethodType: rpc.MethodCall,
			},
		},
	}
}

type KbfsMountClient struct {
	Cli rpc.GenericClient
}

func (c KbfsMountClient) GetCurrentDriveLetter(ctx context.Context) (res string, err error) {
	err = c.Cli.Call(ctx, "keybase.1.kbfsMount.GetCurrentDriveLetter", []interface{}{GetCurrentDriveLetterArg{}}, &res)
	return
}

func (c KbfsMountClient) GetAllAvailableDriveLetters(ctx context.Context) (res []string, err error) {
	err = c.Cli.Call(ctx, "keybase.1.kbfsMount.GetAllAvailableDriveLetters", []interface{}{GetAllAvailableDriveLettersArg{}}, &res)
	return
}

func (c KbfsMountClient) SetCurrentDriveLetter(ctx context.Context, drive string) (err error) {
	__arg := SetCurrentDriveLetterArg{Drive: drive}
	err = c.Cli.Call(ctx, "keybase.1.kbfsMount.SetCurrentDriveLetter", []interface{}{__arg}, nil)
	return
}
